version: '2'
services:
  influxdb:
    image: influxdb
    entrypoint:
      - /opt/rancher/init.sh
    environment:
      - INFLUX_DATABASE="rancherInfra"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: influxdb-config
    volumes_from:
      - influxdb-config
  influxdb-config:
    image: husseingalal/influxdb-config:dev
    volumes:
      - /opt/rancher
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: true
  fluentd:
    image: husseingalal/fluentd-influxdb:dev
    ports:
    - 127.0.0.1:24224:24224/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
